project          = 'giteo'
copyright        = '2021, Ryan Draga'
author           = 'Ryan Draga'
release          = '1.0.0'
extensions       = []
templates_path   = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']
html_theme       = 'alabaster'
html_static_path = ['_static']